sponsors:
  - name: Novoda
    url: https://www.novoda.com/
    logo: novoda.png
  - name: JetBrains
    url: https://www.jetbrains.com/
    logo: jetbrains_logo.png
  - name: Unruly Tech
    url: http://tech.unruly.co/
    logo: unruly.png
